<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Next</name>
   <tag></tag>
   <elementGuidId>58b50330-f888-4330-964d-5936a55a0a7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='Next']//parent::a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#next > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>91c9f47e-51bc-4fec-88c0-090397193d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousemove</name>
      <type>Main</type>
      <value>window.status='';</value>
      <webElementGuid>68460d4e-4420-4bd4-ada5-bbc5b9c9f3bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>window.status='';</value>
      <webElementGuid>4e22631e-c727-406e-941b-d63d5027368b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ccb07ea6-39db-4d65-8ac9-7c6cdbea6160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>63309187-eeab-4cf0-85e9-e9c55beec25b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>DCT.Util.customOnClick(this);DCT.Util.setFocusField('_anchorId');DCT.Util.processInterviewButtonAnchor('next-button_div');</value>
      <webElementGuid>f3015381-12c9-4d5b-97cc-738cad499b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if(DCT.Util.checkSpace(event)){DCT.Util.customOnClick(this);DCT.Util.setFocusField('_anchorId');DCT.Util.processInterviewButtonAnchor('next-button_div');}</value>
      <webElementGuid>b9babc9d-1f17-446f-8be5-7b91db6e973e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>14f3dc34-4fa6-4438-b3bb-c59a73cc93a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;next&quot;)/a[1]</value>
      <webElementGuid>2aaa6274-9da8-460c-b881-1b7e4cf25711</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@name=''])[3]</value>
      <webElementGuid>f7215c51-4e99-4da4-909f-f83a841e8568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='next']/a</value>
      <webElementGuid>ccc7210d-b090-49a0-b6f2-c522249a2666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::a[1]</value>
      <webElementGuid>f6a215cc-dc68-46ad-b0a3-15c9d676a47d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Complete an Application'])[1]/preceding::a[1]</value>
      <webElementGuid>da21e9a8-cf29-46e0-98e7-6d78d2243175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[36]</value>
      <webElementGuid>7128b804-e7bf-497b-9694-b7e9a4147f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/a</value>
      <webElementGuid>345cb242-8fed-4a93-9080-1ead67d2cc38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>b7e3b590-dfe6-4ae1-8b07-f19fef47bedf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
