<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__postalCode</name>
   <tag></tag>
   <elementGuidId>f921cd8b-b3ff-4872-b401-932b11af1fb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@fieldref='AccountInput.ZipCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#f_a2C8E37C240E3448991CA47CEC6B83BBC5C_3_1-inputEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b971c911-ff1d-4ff2-887a-19fa13060c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_a2C8E37C240E3448991CA47CEC6B83BBC5C_3_1-inputEl</value>
      <webElementGuid>ee03c919-143a-4b4d-82bd-47e370ffe67f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>inputEl</value>
      <webElementGuid>e795aa44-d727-42aa-817f-6b2b0415645c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e7d64f7e-e1d3-404a-a1a9-a09e26d599ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fieldref</name>
      <type>Main</type>
      <value>AccountInput.ZipCode</value>
      <webElementGuid>6fa4cc9f-3ba8-4db4-98bb-1ef2693610ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>objectref</name>
      <type>Main</type>
      <value>a2C8E37C240E3448991CA47CEC6B83BBC</value>
      <webElementGuid>b275b4fd-220a-4611-b684-ee26d7aead43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7a2fb7bd-7f1e-456a-971d-9da589f17f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>string_5C|</value>
      <webElementGuid>f7ac4e9d-f087-41e9-aa7f-0302964f06ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>49f799a6-dd07-469c-9278-5ce47d51f323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>18d5e5cb-a371-4545-9281-d924309c9580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8e51f779-2791-495c-9e58-9f3b0f1b5f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>20773c13-118e-44cc-abd9-6c75ba9f0470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3a9ab684-b74a-490e-9273-0242f9069a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7eb7da29-9bd6-4786-832d-b09c513d58c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>f_a2C8E37C240E3448991CA47CEC6B83BBC5C_3_1-ariaStatusEl</value>
      <webElementGuid>6178e82e-295c-4e55-af78-df8a18ac9f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f208c523-d596-4091-ada8-6fc9a9895ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-field x-form-required-field x-form-text x-form-text-default  x-form-focus x-field-form-focus x-field-default-form-focus</value>
      <webElementGuid>7541c933-1b5f-4435-8239-99c2998cba83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a8567c4c-2d68-4e49-b98f-c420289d397f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-componentid</name>
      <type>Main</type>
      <value>f_a2C8E37C240E3448991CA47CEC6B83BBC5C_3_1</value>
      <webElementGuid>33a2ae2e-6e87-48c7-a2c5-13491463730e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_a2C8E37C240E3448991CA47CEC6B83BBC5C_3_1-inputEl&quot;)</value>
      <webElementGuid>b6cecbf8-66be-4deb-aff3-fb92c6b031ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_a2C8E37C240E3448991CA47CEC6B83BBC5C_3_1-inputEl']</value>
      <webElementGuid>9206a744-4116-4f81-97fd-fa039a523e96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='f_a2C8E37C240E3448991CA47CEC6B83BBC5C_3_1-inputWrap']/input</value>
      <webElementGuid>f835a18a-15d7-4197-859c-73f19e91a988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>1cc4e4f2-ecf5-4782-8240-343589539883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'f_a2C8E37C240E3448991CA47CEC6B83BBC5C_3_1-inputEl' and @type = 'text' and @name = 'string_5C|']</value>
      <webElementGuid>b02a381c-e8ba-4436-a2c6-9fc08da51a33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
