<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_emailAddress</name>
   <tag></tag>
   <elementGuidId>eb8a4c03-cee4-48df-9896-798c83faa126</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@fieldref='AccountInput.Email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#f_a2C8E37C240E3448991CA47CEC6B83BBC4F_3_1-inputEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0136a976-efd4-4310-afa1-83d7426e3e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_a2C8E37C240E3448991CA47CEC6B83BBC4F_3_1-inputEl</value>
      <webElementGuid>c6c9f361-cf23-4682-b9b7-e4f8becda001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>inputEl</value>
      <webElementGuid>f3dab66a-f8c8-46c5-9cc6-8eff340d2768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>21163abe-b3e3-45a2-85e1-11e25a108c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fieldref</name>
      <type>Main</type>
      <value>AccountInput.Email</value>
      <webElementGuid>4be097d7-a0d5-44cb-baf7-5b7b78f0b4cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>objectref</name>
      <type>Main</type>
      <value>a2C8E37C240E3448991CA47CEC6B83BBC</value>
      <webElementGuid>49962bb3-133e-43ae-8b99-5ed0d5f57990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8559e46b-4cf1-4aef-b6c9-433a09f1d980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>string_4F|</value>
      <webElementGuid>b8fefcb6-6c01-40a2-a1e6-1a8d86a26056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>f1884e60-39df-4a2d-baa4-2f3d312033c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>41a47b81-2991-4766-8a1a-c91445912a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>384f2d95-239a-47f7-8018-506ae9584939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>99c110a3-db74-40db-8e4e-9cb6657b680c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cc395eb6-80fd-4c4a-be17-ab3b14e0542f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d17fa5ff-736a-49bc-adfa-614d7cd7361d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>f_a2C8E37C240E3448991CA47CEC6B83BBC4F_3_1-ariaStatusEl</value>
      <webElementGuid>9e46b833-a8e9-4ea1-a31c-24bafbd34bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5229a9cb-6922-4163-bcf0-1fe53072c84a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-field x-form-text x-form-text-default  x-form-focus x-field-form-focus x-field-default-form-focus</value>
      <webElementGuid>ea54baeb-12e0-4bcf-ad0e-ec976a2fe17b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ca02d2ff-8033-4035-92fe-09b13cb6136e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-componentid</name>
      <type>Main</type>
      <value>f_a2C8E37C240E3448991CA47CEC6B83BBC4F_3_1</value>
      <webElementGuid>6d5b7385-426b-40d7-a793-6133b118166a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_a2C8E37C240E3448991CA47CEC6B83BBC4F_3_1-inputEl&quot;)</value>
      <webElementGuid>e5883d44-01f6-4d27-9058-de41b5ceee2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_a2C8E37C240E3448991CA47CEC6B83BBC4F_3_1-inputEl']</value>
      <webElementGuid>e5a52b02-639f-4668-b9ac-796cb0ef4e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='f_a2C8E37C240E3448991CA47CEC6B83BBC4F_3_1-inputWrap']/input</value>
      <webElementGuid>e96f6086-8e10-48fa-aa3a-ff98671cb74c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/div/div/div/input</value>
      <webElementGuid>f6b7e876-7343-473f-ac23-b62b1b1e937c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'f_a2C8E37C240E3448991CA47CEC6B83BBC4F_3_1-inputEl' and @type = 'text' and @name = 'string_4F|']</value>
      <webElementGuid>478c2e9d-cb53-4eda-83d9-78c5116d9cf0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
