<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__lastName</name>
   <tag></tag>
   <elementGuidId>7efd175b-e3bf-4787-824b-e0799b77680f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@fieldref='AccountInput.LastName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#f_a2C8E37C240E3448991CA47CEC6B83BBC3D_3_1-inputEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f12acd4-c4a5-4584-9f8a-349af02201c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_a2C8E37C240E3448991CA47CEC6B83BBC3D_3_1-inputEl</value>
      <webElementGuid>66ba6b4d-694b-4a0a-8cb0-c7dc918b271c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>inputEl</value>
      <webElementGuid>3f9ccf9b-61bf-4444-8aa4-2593c7fc77dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>465b3692-c2e5-43ee-95be-3e427dab00c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fieldref</name>
      <type>Main</type>
      <value>AccountInput.LastName</value>
      <webElementGuid>4c7058f7-3e5a-45fc-80e7-bc8679c5574d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>objectref</name>
      <type>Main</type>
      <value>a2C8E37C240E3448991CA47CEC6B83BBC</value>
      <webElementGuid>39341c99-cd2d-4521-b5b1-ff78cddb0217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e7ab9ed3-9bf0-4dd4-8fdf-487bb0775839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>string_3D|</value>
      <webElementGuid>4208d99e-ece9-4a58-82e2-ffeb0d159db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>64e71ff3-492f-44c7-a6ca-d2d0f9c08505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b433da1c-0da3-4a0d-8255-6933efbe3916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d645361c-6fcb-4460-adb6-84f971aee9eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>8174be5c-9297-4ec8-af03-52f54d8f2a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>95262430-049d-499a-8d71-6ec817e9c996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e9edd5f2-1625-4bdd-a1d4-248155a5f314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>f_a2C8E37C240E3448991CA47CEC6B83BBC3D_3_1-ariaStatusEl</value>
      <webElementGuid>4f305c52-843f-44f4-bbfe-27724b169d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0d46fbd1-0867-4c8e-a1ae-618cce0f3c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-field x-form-required-field x-form-text x-form-text-default  x-form-focus x-field-form-focus x-field-default-form-focus</value>
      <webElementGuid>42204f93-ec06-4a57-bca7-8c5101919742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c04a6522-2a4e-49be-9af8-df4270e79f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-componentid</name>
      <type>Main</type>
      <value>f_a2C8E37C240E3448991CA47CEC6B83BBC3D_3_1</value>
      <webElementGuid>82c64756-07de-4b37-84d6-c26255de2d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_a2C8E37C240E3448991CA47CEC6B83BBC3D_3_1-inputEl&quot;)</value>
      <webElementGuid>6b64aae3-02e2-4d7d-a3e3-f2695c6ad82a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_a2C8E37C240E3448991CA47CEC6B83BBC3D_3_1-inputEl']</value>
      <webElementGuid>8b1623f1-6424-4fb7-9f61-abb55991c354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='f_a2C8E37C240E3448991CA47CEC6B83BBC3D_3_1-inputWrap']/input</value>
      <webElementGuid>79a30734-1843-4a75-a07e-67e2ccad8269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>822061c0-cc72-4edf-9a1a-69aa03a360ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'f_a2C8E37C240E3448991CA47CEC6B83BBC3D_3_1-inputEl' and @type = 'text' and @name = 'string_3D|']</value>
      <webElementGuid>c681b786-6cb1-4016-9afd-7d1c0188fafe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
