<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__f_r3DD2E6831B214154B14D61FA4853FA075_f0e583</name>
   <tag></tag>
   <elementGuidId>ba64bafe-b29a-47ae-9684-51ae70288930</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f_r3DD2E6831B214154B14D61FA4853FA0751_1_1-inputEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@data-ref='inputEl' and @fieldRef='data.VersionIDPages']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1143f19-7ee6-40d2-a03f-bd46676d2783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_r3DD2E6831B214154B14D61FA4853FA0751_1_1-inputEl</value>
      <webElementGuid>6ed37812-6373-4eb7-a311-9b143bb1092e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>inputEl</value>
      <webElementGuid>f3507168-0c4a-4add-8fa0-dcf29063f3f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a266f982-b7b0-4968-8d5c-98cb603f05ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fieldref</name>
      <type>Main</type>
      <value>data.VersionIDPages</value>
      <webElementGuid>1be40be1-208f-4d6f-9db6-caf4a315b522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>objectref</name>
      <type>Main</type>
      <value>r3DD2E6831B214154B14D61FA4853FA07</value>
      <webElementGuid>ec2a926b-0a8e-4f20-b3ad-7f21f3cf1f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ba1f9658-00f3-4b84-994f-b0e492af0fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>f_r3DD2E6831B214154B14D61FA4853FA0751_1_1-inputEl</value>
      <webElementGuid>489d3b6e-85cd-4378-bf1d-c9403d953fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>(select product)</value>
      <webElementGuid>fc0c8ed3-35f0-4355-a122-8a333a9b02ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>(select product)</value>
      <webElementGuid>1356b21a-11f0-459b-a2f6-4766208a2b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4472f9f5-b967-4311-b6e9-cee9c75e289f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6a3eb1ca-aa18-459c-ac18-af7ebeb224fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>8a88691b-d970-4d9a-a410-41acb3e1a918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ac9b543d-3e48-49d6-956b-b182bf028d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ec066799-ef1a-4e1e-bf1a-2b357d26ac3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>f_r3DD2E6831B214154B14D61FA4853FA0751_1_1-inputEl f_r3DD2E6831B214154B14D61FA4853FA0751_1_1-picker-listEl</value>
      <webElementGuid>56eb4ff4-627f-477b-ba89-1ce028cb7ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>de112d14-0769-4a6e-9431-b7bfa8845240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f9510959-0b48-42db-8875-78a5fb21ecbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b260d39e-84e8-4c7a-ac3b-020a2fba3304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>f_r3DD2E6831B214154B14D61FA4853FA0751_1_1-ariaStatusEl</value>
      <webElementGuid>1da0ee9e-f262-40f5-bd46-8dce7386e70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>24f9a676-4906-48e7-b69f-e957078d9d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-field x-form-required-field x-form-text x-form-text-default  x-form-focus x-field-form-focus x-field-default-form-focus</value>
      <webElementGuid>d7a213cd-0596-4e58-ba4f-9c5f2fc5d621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2ec09126-61b4-4bf0-8f4e-7d1b480e3003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-componentid</name>
      <type>Main</type>
      <value>f_r3DD2E6831B214154B14D61FA4853FA0751_1_1</value>
      <webElementGuid>ccf5d8cc-4e0e-4a5b-af26-a5a466c3397d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_r3DD2E6831B214154B14D61FA4853FA0751_1_1-inputEl&quot;)</value>
      <webElementGuid>97f57d46-1faf-4185-8fe0-c07c478dadea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_r3DD2E6831B214154B14D61FA4853FA0751_1_1-inputEl']</value>
      <webElementGuid>cfa74366-67fd-4948-bf92-f88b26209b8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='f_r3DD2E6831B214154B14D61FA4853FA0751_1_1-inputWrap']/input</value>
      <webElementGuid>4251451b-0252-47af-9468-a61d96f2eef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[4]/div[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>4f169418-96db-4bff-b935-dc7504d4836a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'f_r3DD2E6831B214154B14D61FA4853FA0751_1_1-inputEl' and @type = 'text' and @name = 'f_r3DD2E6831B214154B14D61FA4853FA0751_1_1-inputEl' and @placeholder = '(select product)']</value>
      <webElementGuid>19b8b177-0d65-42b4-8882-11afc713d754</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
