<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_AUS Personal Lines Motor (1.0.0.0)</name>
   <tag></tag>
   <elementGuidId>bfe6f8c1-42c4-4377-85cf-8139a6710b3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ext-element-64</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@data-qtip='AUS Personal Lines Motor (1.0.0.0)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>0d785263-c2c4-4d80-835e-aa51d460c834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>39677339-115c-4979-b63b-ad4b9c116ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>6c9be6e6-e3f5-4dc1-9820-ba2fa94ef46b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-boundlist-item x-boundlist-item-over</value>
      <webElementGuid>738617f5-2852-4c32-9776-25d7c04351c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qtip</name>
      <type>Main</type>
      <value>AUS Personal Lines Motor (1.0.0.0)</value>
      <webElementGuid>5ab958b4-a6e5-491a-88a6-b0fc69371686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>720160d0-04ec-444b-aead-29b175d2298a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recordindex</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>39bd5aaf-29d2-439e-8bf7-8d1e6b3537d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recordid</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>1fbe858d-52f6-4b07-af46-88cb1c7b078e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-boundview</name>
      <type>Main</type>
      <value>f_r3DD2E6831B214154B14D61FA4853FA0751_1_1-picker</value>
      <webElementGuid>f385600a-8f68-4ad6-b64e-e71246c646c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ext-element-64</value>
      <webElementGuid>f6b320b5-7b56-4c80-a9fe-a8982062d216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AUS Personal Lines Motor (1.0.0.0)</value>
      <webElementGuid>80d8fc5d-4c0a-4b65-80b3-04488a3dc5aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-element-64&quot;)</value>
      <webElementGuid>bd8108d0-fde3-4801-9e2b-bd94a7ebf676</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='ext-element-64']</value>
      <webElementGuid>c27d238d-0137-4b94-a546-04ca4d4d9282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='f_r3DD2E6831B214154B14D61FA4853FA0751_1_1-picker-listEl']/li[8]</value>
      <webElementGuid>b901f0e6-d434-43df-845c-1584ea13858c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUS Carrier Personal Lines Motor (1.0.0.0)'])[1]/following::li[1]</value>
      <webElementGuid>70558146-35b3-40d7-870f-7df66d5e4f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DCT Sample Product (3.0.0.0)'])[1]/following::li[2]</value>
      <webElementGuid>d1f282f4-60a0-4a84-8ec4-e74491ca4e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QA Test Lab'])[1]/preceding::li[1]</value>
      <webElementGuid>4ffa0d80-960c-4786-850c-fa8ebc5bf269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Carrier_Integration_Pages_US_1_0_0_0'])[1]/preceding::li[2]</value>
      <webElementGuid>7b4f541b-0f9d-4c13-88b3-b51676c100d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]</value>
      <webElementGuid>ddd91d74-6bbc-4961-8a5b-341cb0bec34e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'ext-element-64' and (text() = 'AUS Personal Lines Motor (1.0.0.0)' or . = 'AUS Personal Lines Motor (1.0.0.0)')]</value>
      <webElementGuid>caf2bcdf-0c22-4e3e-a696-5e70189dc8f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
