<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Policy Term</name>
   <tag></tag>
   <elementGuidId>03590b74-e4ea-414f-86e0-9f683dbd71ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pageTitle' and text() = 'Policy Term']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pageTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>81a5e2dd-8641-4a2e-b782-5efa7c85b64e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pageTitle</value>
      <webElementGuid>4d225046-c3dc-496e-9d88-f813d46c3529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Policy Term</value>
      <webElementGuid>4262c988-ee06-42ee-9a33-7c5045b0f060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pageTitle&quot;)</value>
      <webElementGuid>58092eb5-5db6-45be-ac92-c09a7e93e8b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='pageTitle']</value>
      <webElementGuid>a5a432ce-2a80-4fb5-93c5-770423207706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pageTop']/div</value>
      <webElementGuid>aeaa54fa-23a3-468b-961d-d8f4c9e339e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No active item'])[1]/following::div[3]</value>
      <webElementGuid>fdc6f7b9-2b2e-4e78-aaad-3e0b84826224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instalment Schedule'])[1]/following::div[4]</value>
      <webElementGuid>48232488-f514-4988-91fd-92a8ae2a91b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::div[13]</value>
      <webElementGuid>ac9e48db-6a6a-4d75-b76f-3b59097f4e0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div</value>
      <webElementGuid>6f2142c8-4dca-4987-896a-196c9dd4b99c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'pageTitle' and (text() = 'Policy Term' or . = 'Policy Term')]</value>
      <webElementGuid>fba11694-633f-4555-9d16-bacd9f38db86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
