<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Driver(s)</name>
   <tag></tag>
   <elementGuidId>602c95a7-fda7-4a14-951a-bda6fbd620af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pageTitle' and text()='Driver(s)']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pageTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bf4bc639-6de4-4ed4-8f31-36e095020112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pageTitle</value>
      <webElementGuid>21f47669-9f34-41e5-9f87-a5f3ca959a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Driver(s)</value>
      <webElementGuid>abf1ebd9-54ba-4890-8f07-389c7e3069bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pageTitle&quot;)</value>
      <webElementGuid>b7786da1-f049-4db0-b5ea-99a2daa139d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='pageTitle']</value>
      <webElementGuid>6ce94935-7c29-470b-b518-ebd3af1ca80e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pageTop']/div</value>
      <webElementGuid>7721eb78-828a-4314-9f3e-09dd900869b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No active item'])[1]/following::div[3]</value>
      <webElementGuid>a24be215-03de-4dc3-a89b-58e3e9916338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instalment Schedule'])[1]/following::div[4]</value>
      <webElementGuid>0e6524f3-ff06-4479-9c74-91893b72e351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div</value>
      <webElementGuid>c4662f21-44c4-4a73-8218-3d44a8807479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'pageTitle' and (text() = 'Driver(s)' or . = 'Driver(s)')]</value>
      <webElementGuid>cc410d0b-7b7d-47e7-8555-aa0dbb7d4225</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
