<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_GenderM</name>
   <tag></tag>
   <elementGuidId>75a7e996-e714-4ac2-a007-a2409a51b051</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@fieldref='DriverInput.Gender' and @value='M']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#f_d2890346873AE42FA926327299BFD43B7C4_3_1_0-inputEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>be5e6dd4-0d5f-470f-ab15-bc9f280dcd84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>23dd97dd-f52e-4c4b-90f9-2af118bc04ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_d2890346873AE42FA926327299BFD43B7C4_3_1_0-inputEl</value>
      <webElementGuid>33bc1de3-056e-4b58-8660-fcb91e32ab42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>string_C4</value>
      <webElementGuid>fdad8cbc-7cc9-4f1f-9ed3-00584309323a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>inputEl</value>
      <webElementGuid>afafb933-5520-4554-846f-59438131cca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>28a792e0-91a8-439a-ac67-1af2ce9e9727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fieldref</name>
      <type>Main</type>
      <value>DriverInput.Gender</value>
      <webElementGuid>768c6218-16a3-4917-b301-a0796900c84b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>objectref</name>
      <type>Main</type>
      <value>d2890346873AE42FA926327299BFD43B7</value>
      <webElementGuid>7fe21e16-6b83-409d-9f1d-2a5be855cf2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>99676448-9c81-428f-a56c-2ee90435dbe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-cb-input</value>
      <webElementGuid>0d4d7442-3b1b-430d-9dba-385cece14267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>883d6434-f0cd-42e2-a96d-a5854269a0ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hidefocus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>19d4278f-028c-4344-818c-e25f6a5166ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c9d31b4e-3cd9-4f7d-ba2f-ade94448d5f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>366a42f2-47da-46dd-b311-7271e7ef570c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7f077aeb-764f-41fb-882d-d157fb4f280e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>f_d2890346873AE42FA926327299BFD43B7C4_3_1_0-ariaStatusEl</value>
      <webElementGuid>2943b121-8be3-4860-ae25-44ac0ee577ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-componentid</name>
      <type>Main</type>
      <value>f_d2890346873AE42FA926327299BFD43B7C4_3_1_0</value>
      <webElementGuid>2ec4cd55-63da-4e46-a66d-a05edd317133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_d2890346873AE42FA926327299BFD43B7C4_3_1_0-inputEl&quot;)</value>
      <webElementGuid>8ea2e997-5179-45f8-b3c3-890f31bc38d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_d2890346873AE42FA926327299BFD43B7C4_3_1_0-inputEl']</value>
      <webElementGuid>c854f6b2-9b20-4b35-b75f-c28e1c82911d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='f_d2890346873AE42FA926327299BFD43B7C4_3_1_0-displayEl']/input</value>
      <webElementGuid>7e54258a-ce1e-4f6b-94a4-c1ed624d5673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>3bf66f7d-a032-4e12-81b6-80141cd52fc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'f_d2890346873AE42FA926327299BFD43B7C4_3_1_0-inputEl' and @name = 'string_C4' and @checked = 'checked']</value>
      <webElementGuid>929b4cb7-b959-46d7-b732-20023aac171d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
