<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_financed</name>
   <tag></tag>
   <elementGuidId>26812479-70ce-41cf-8d44-ca0ea4f79d2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@fieldref='VehicleInput.FinancialStatus']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#f_v66B56BB498ED4B16A56D62EFFDD04C7C99_3_1-inputEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aec86751-9cf3-40f6-8f28-e5904c2b8dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_v66B56BB498ED4B16A56D62EFFDD04C7C99_3_1-inputEl</value>
      <webElementGuid>8e102b87-af7c-489d-8db3-acb3d49d264f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>inputEl</value>
      <webElementGuid>a6eb99dc-4e28-4f9a-a26f-d1333989c51c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>88c442f4-2808-4fe1-93a0-5598b116c6f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fieldref</name>
      <type>Main</type>
      <value>VehicleInput.FinancialStatus</value>
      <webElementGuid>572ed0e3-c8d4-4b3d-a28f-fc92d3ff932a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>objectref</name>
      <type>Main</type>
      <value>v66B56BB498ED4B16A56D62EFFDD04C7C</value>
      <webElementGuid>b9eafc7b-a228-4692-afbc-c92ffeb2634a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>633c08fe-45ee-4a38-9813-f4c864dbf7f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>f_v66B56BB498ED4B16A56D62EFFDD04C7C99_3_1-inputEl</value>
      <webElementGuid>e446e77c-4ae1-4933-b2da-1648a2ac1daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>(select)</value>
      <webElementGuid>bff2b2b0-fe9f-469a-b260-966e8b3246a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>(select)</value>
      <webElementGuid>fa843145-2d82-4347-9ade-d3d745684b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f9632c29-4efa-4af4-88fb-98ba16ceef4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8348095d-4e71-4be1-a55b-dc20c900677e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>251b9ed2-753e-402a-b18e-3d5c03ba6906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a81d6635-e5c0-4781-a243-2c95776b5774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9dce56e9-cddb-457a-86de-959d1b065ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>f_v66B56BB498ED4B16A56D62EFFDD04C7C99_3_1-inputEl f_v66B56BB498ED4B16A56D62EFFDD04C7C99_3_1-picker-listEl</value>
      <webElementGuid>2310f63a-3a00-4279-a6c2-b842f6ee8ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>2696e7ce-6866-4b91-b038-679bbcdba3ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e8166e4f-7fb2-44bb-959e-40e6d1b1ebf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b2b9d5e7-f7ac-4add-b1d1-f3223c9ca15d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>f_v66B56BB498ED4B16A56D62EFFDD04C7C99_3_1-ariaStatusEl</value>
      <webElementGuid>686348d5-ae22-4855-ae49-03555f8b968b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>037fe253-5bc4-49d2-b943-a63dd321f5a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-field x-form-required-field x-form-text x-form-text-default  x-form-focus x-field-form-focus x-field-default-form-focus</value>
      <webElementGuid>af1121fc-8e68-4496-a367-c2b4c2d0bc82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d2d993af-2df7-4c11-88e9-fc6517d41b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-componentid</name>
      <type>Main</type>
      <value>f_v66B56BB498ED4B16A56D62EFFDD04C7C99_3_1</value>
      <webElementGuid>1dcd2c11-7af4-4187-8ec2-7c9e0c2a852f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_v66B56BB498ED4B16A56D62EFFDD04C7C99_3_1-inputEl&quot;)</value>
      <webElementGuid>f08f4a6b-b454-4371-b665-8292727411b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_v66B56BB498ED4B16A56D62EFFDD04C7C99_3_1-inputEl']</value>
      <webElementGuid>97eb24cd-10ae-4b59-b8cf-35f98cab08b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='f_v66B56BB498ED4B16A56D62EFFDD04C7C99_3_1-inputWrap']/input</value>
      <webElementGuid>5dced367-af8a-4dbf-aefd-5a48abbf41e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[3]/div[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>c0e835d2-ae59-4b00-8c43-52994d43f166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'f_v66B56BB498ED4B16A56D62EFFDD04C7C99_3_1-inputEl' and @type = 'text' and @name = 'f_v66B56BB498ED4B16A56D62EFFDD04C7C99_3_1-inputEl' and @placeholder = '(select)']</value>
      <webElementGuid>fbc94007-2351-4d84-8912-230b0c3a48b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
