<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__modelYear</name>
   <tag></tag>
   <elementGuidId>3593ff2c-8b99-4c00-bd79-8a5ec53afb0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@fieldref='VehicleInput.Year']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#f_v66B56BB498ED4B16A56D62EFFDD04C7C7F_3_1-inputEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6acdbf6-3cbb-4050-bd70-42e13fb23972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_v66B56BB498ED4B16A56D62EFFDD04C7C7F_3_1-inputEl</value>
      <webElementGuid>16b9c14d-7fc3-423c-8106-ddd92691de7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>inputEl</value>
      <webElementGuid>55759698-f690-4ba3-8d98-d53d64b3f156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>85dfdd5d-649a-45da-b3d8-9843a50dc890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fieldref</name>
      <type>Main</type>
      <value>VehicleInput.Year</value>
      <webElementGuid>1acb8686-c079-441a-9130-9cd97e12efc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>objectref</name>
      <type>Main</type>
      <value>v66B56BB498ED4B16A56D62EFFDD04C7C</value>
      <webElementGuid>451e8876-0ec1-4c1e-b573-dd30d1a15dbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f2fd3871-bad1-413f-b317-d3f0f6056c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>f_v66B56BB498ED4B16A56D62EFFDD04C7C7F_3_1-inputEl</value>
      <webElementGuid>a179b0ac-0e78-4b3b-b163-b23ca3b1a219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>(Select)</value>
      <webElementGuid>0dff3053-aecf-4d13-84d6-0e0c8981386f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>299008ab-e0fd-4292-8f18-6e38dc0bc963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>efc0a286-415d-46c1-a9de-af21e692fc07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>03258674-510c-4bf6-b39b-ec3e03241526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8cfb5b8b-9b04-4094-9f1f-cecd971cdcad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>42898133-d16a-4489-bb92-053b76a69b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>f_v66B56BB498ED4B16A56D62EFFDD04C7C7F_3_1-inputEl f_v66B56BB498ED4B16A56D62EFFDD04C7C7F_3_1-picker-listEl</value>
      <webElementGuid>9c74d9b8-0407-4a5a-a73f-c88b73babddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>fe6604ab-7677-47d6-b72a-df927faf01e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e68cd4e2-4cf7-4c4a-aad2-e50db400c1a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e99de13c-9a47-4f42-962f-52fb61119f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>f_v66B56BB498ED4B16A56D62EFFDD04C7C7F_3_1-ariaStatusEl</value>
      <webElementGuid>c58ecc34-ac21-4bad-acd9-5a5c5b15d457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>03471c88-4f6e-430e-b6a3-b78a9670c488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-field x-form-required-field x-form-empty-field x-form-empty-field-default x-form-text x-form-text-default  x-form-focus x-field-form-focus x-field-default-form-focus</value>
      <webElementGuid>7aa75341-5385-414d-93b9-c81bd610d482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b0d27b0a-56fd-4db7-a5fe-fa8f5622df9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-componentid</name>
      <type>Main</type>
      <value>f_v66B56BB498ED4B16A56D62EFFDD04C7C7F_3_1</value>
      <webElementGuid>9d0d912b-6182-4aba-bb32-28ca3b4e5e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_v66B56BB498ED4B16A56D62EFFDD04C7C7F_3_1-inputEl&quot;)</value>
      <webElementGuid>aa15aa5e-6dd4-44ef-9db2-acd828387fdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_v66B56BB498ED4B16A56D62EFFDD04C7C7F_3_1-inputEl']</value>
      <webElementGuid>a242f318-d958-4f95-829d-6a4648aad921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='f_v66B56BB498ED4B16A56D62EFFDD04C7C7F_3_1-inputWrap']/input</value>
      <webElementGuid>205b5888-53aa-4c5d-b3b5-adde297cb58b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>ab203bab-bf29-4940-b0c8-1d5d59a1b1e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'f_v66B56BB498ED4B16A56D62EFFDD04C7C7F_3_1-inputEl' and @type = 'text' and @name = 'f_v66B56BB498ED4B16A56D62EFFDD04C7C7F_3_1-inputEl' and @placeholder = '(Select)']</value>
      <webElementGuid>b82a36e8-89f5-4b2e-9b27-f5f4c5719365</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
