<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__make</name>
   <tag></tag>
   <elementGuidId>8d7e46af-1c6a-4e13-ad55-b203180694d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@fieldref='VehicleInput.Make']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#f_v66B56BB498ED4B16A56D62EFFDD04C7C80_3_1-inputEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8dbb887a-52d3-4bbf-94f2-e3debdb877ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f_v66B56BB498ED4B16A56D62EFFDD04C7C80_3_1-inputEl</value>
      <webElementGuid>3ec51e11-6f50-4a6c-978b-e67b8f7a092f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>inputEl</value>
      <webElementGuid>7c73166b-4f93-4fdd-b038-e88e58d65236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0874ac86-4d7a-4397-bbfe-d03957db7a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fieldref</name>
      <type>Main</type>
      <value>VehicleInput.Make</value>
      <webElementGuid>fe185fef-1844-487f-8e11-da0a793235b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>objectref</name>
      <type>Main</type>
      <value>v66B56BB498ED4B16A56D62EFFDD04C7C</value>
      <webElementGuid>d9ac7f2a-78d6-46a5-8ead-7657a615d7e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2d50937a-d4fc-4ed1-b078-8dd711486d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>f_v66B56BB498ED4B16A56D62EFFDD04C7C80_3_1-inputEl</value>
      <webElementGuid>9c5e6b97-4d0f-4326-b152-66c7f16e598f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>(select)</value>
      <webElementGuid>a1faa787-01f2-4b3c-8c77-e3a53fbef3f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>(select)</value>
      <webElementGuid>9c296786-92f5-43fe-bdef-ff3889777f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9a851c59-922f-48a8-bb2c-93afe1129b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>91fbcb7e-bf1c-4235-95e0-be13c0864e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>f67e4da6-ca37-47be-9e63-3405666e1458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a6a86f55-8504-4a50-b895-a6a1c310fe22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>893e0fcc-d9a9-4fa3-9cd7-5608ad8f8b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>f_v66B56BB498ED4B16A56D62EFFDD04C7C80_3_1-inputEl f_v66B56BB498ED4B16A56D62EFFDD04C7C80_3_1-picker-listEl</value>
      <webElementGuid>26355896-b892-4151-a3b0-a20e735506d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>53463c4e-cffd-49d7-bb06-34bd725bdd7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>30bceee1-0f37-4ab3-9991-1236e39b9af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>352871fc-c593-44eb-aa26-a504e1c236ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>f_v66B56BB498ED4B16A56D62EFFDD04C7C80_3_1-ariaStatusEl</value>
      <webElementGuid>74b7dd5e-66ca-4c3a-a2c3-cd078b011c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dcaa64f2-398e-4201-8e4d-dfc6d30c83ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-field x-form-required-field x-form-text x-form-text-default  x-form-focus x-field-form-focus x-field-default-form-focus</value>
      <webElementGuid>af8da286-71a3-460a-9681-45882974380e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b04f1dc6-a3b3-467d-b0a9-a24d1c599878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-componentid</name>
      <type>Main</type>
      <value>f_v66B56BB498ED4B16A56D62EFFDD04C7C80_3_1</value>
      <webElementGuid>f7c2813a-a008-4ba0-8047-f2fcaf6a92a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_v66B56BB498ED4B16A56D62EFFDD04C7C80_3_1-inputEl&quot;)</value>
      <webElementGuid>8743760d-7f3b-4332-a0a0-1a5805ac2d8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f_v66B56BB498ED4B16A56D62EFFDD04C7C80_3_1-inputEl']</value>
      <webElementGuid>d69a03e2-49ff-43c4-8b15-7d3c5f7e6ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='f_v66B56BB498ED4B16A56D62EFFDD04C7C80_3_1-inputWrap']/input</value>
      <webElementGuid>367d8ca9-d25c-42ce-a2d9-30c7a1236d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>102bdbfa-78de-4b02-9fff-5650caf225dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'f_v66B56BB498ED4B16A56D62EFFDD04C7C80_3_1-inputEl' and @type = 'text' and @name = 'f_v66B56BB498ED4B16A56D62EFFDD04C7C80_3_1-inputEl' and @placeholder = '(select)']</value>
      <webElementGuid>52f0128f-ec2f-45d0-8695-2f67454edd82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
