<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Model</name>
   <tag></tag>
   <elementGuidId>dc79de6d-ca78-4a1f-aa78-b58e0a1f0075</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='c_v66B56BB498ED4B16A56D62EFFDD04C7C81_3_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c_v66B56BB498ED4B16A56D62EFFDD04C7C81_3_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>7ff1bb53-18e4-4475-b446-436d2c0931f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c_v66B56BB498ED4B16A56D62EFFDD04C7C81_3_1</value>
      <webElementGuid>30b7de07-b7e4-4452-bd46-c7a1cadc5f23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>f_v66B56BB498ED4B16A56D62EFFDD04C7C81_3_1</value>
      <webElementGuid>809a23c6-fe19-4005-ab3c-cedd86f6ed05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>requiredField </value>
      <webElementGuid>35c8fb83-250f-4982-ac62-8cf77e35842d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Model:*</value>
      <webElementGuid>2cc6a8a8-8fc7-44bb-8e23-c64cea18ec05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c_v66B56BB498ED4B16A56D62EFFDD04C7C81_3_1&quot;)</value>
      <webElementGuid>57e44192-3429-4e8e-b232-052840814118</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='c_v66B56BB498ED4B16A56D62EFFDD04C7C81_3_1']</value>
      <webElementGuid>be5f5d5e-e441-4a42-bcbf-042e906b5130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='downFieldGroupc_v66B56BB498ED4B16A56D62EFFDD04C7C81_3_1']/div/label</value>
      <webElementGuid>6f834fa4-ac4a-4401-bf17-4638e2f01c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::label[2]</value>
      <webElementGuid>f4947da9-d724-4240-9701-8f5ce98a420a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Model:']/parent::*</value>
      <webElementGuid>424aa5ce-fcf2-4782-aac1-4ed901e73af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[4]/div/label</value>
      <webElementGuid>bce92a40-f336-4400-af81-05a9f0f094c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'c_v66B56BB498ED4B16A56D62EFFDD04C7C81_3_1' and (text() = 'Model:*' or . = 'Model:*')]</value>
      <webElementGuid>98e3fdee-e33f-4eb1-9ab7-214196d70753</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
