<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Description</name>
   <tag></tag>
   <elementGuidId>a00cea5d-552b-46b2-bf05-a45ffee66e69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='c_v66B56BB498ED4B16A56D62EFFDD04C7C82_3_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c_v66B56BB498ED4B16A56D62EFFDD04C7C82_3_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>0fc7484f-f123-4247-9f1a-51af06ae4ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c_v66B56BB498ED4B16A56D62EFFDD04C7C82_3_1</value>
      <webElementGuid>24f2eb9a-ce97-419f-8680-82f1b428eac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>f_v66B56BB498ED4B16A56D62EFFDD04C7C82_3_1</value>
      <webElementGuid>c66c64c7-e805-4e7f-a511-8d26bac3e739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>requiredField </value>
      <webElementGuid>dac91141-2ab8-4f0a-8457-55f7bfad9a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Description:*</value>
      <webElementGuid>8f8e95b6-408c-4381-a96c-4929872b7620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c_v66B56BB498ED4B16A56D62EFFDD04C7C82_3_1&quot;)</value>
      <webElementGuid>917b2c02-6d91-4c45-9435-f0a936624e7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='c_v66B56BB498ED4B16A56D62EFFDD04C7C82_3_1']</value>
      <webElementGuid>75369328-b2a5-45f2-9ffb-72689bbcc8a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='downFieldGroupc_v66B56BB498ED4B16A56D62EFFDD04C7C82_3_1']/div/label</value>
      <webElementGuid>282824b2-f0c1-489f-8939-bd015238c57c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::label[2]</value>
      <webElementGuid>68846fac-7dde-4b38-95f8-c464604af4ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Does your vehicle have any additional accessories, modifications or security devices fitted?'])[1]/preceding::label[2]</value>
      <webElementGuid>65dfbc19-2109-495a-97e0-1b7fce014a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Description:']/parent::*</value>
      <webElementGuid>4f12d9da-0f1a-4215-8cf6-9de97c58c725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[5]/div/label</value>
      <webElementGuid>64a329c3-4632-433f-a16f-ff7fef172132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'c_v66B56BB498ED4B16A56D62EFFDD04C7C82_3_1' and (text() = 'Description:*' or . = 'Description:*')]</value>
      <webElementGuid>4b8d841c-df46-49b2-85b0-6f116e2f78dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
