<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Make</name>
   <tag></tag>
   <elementGuidId>5fa81d71-bade-4bc0-8324-8d3273458ef4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='c_v66B56BB498ED4B16A56D62EFFDD04C7C80_3_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c_v66B56BB498ED4B16A56D62EFFDD04C7C80_3_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>00be512a-85bf-46c6-af56-56c342e87170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c_v66B56BB498ED4B16A56D62EFFDD04C7C80_3_1</value>
      <webElementGuid>8add7f46-7a20-4eb2-beb6-e02730382b5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>f_v66B56BB498ED4B16A56D62EFFDD04C7C80_3_1</value>
      <webElementGuid>da9ab41c-1d32-47ee-9f63-6c2cbb435b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>requiredField </value>
      <webElementGuid>7528b4cd-282b-43f5-bca6-3b9e87c7eec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Make:*</value>
      <webElementGuid>7c18ffb6-d207-48a9-80ec-75df63512847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c_v66B56BB498ED4B16A56D62EFFDD04C7C80_3_1&quot;)</value>
      <webElementGuid>ff36532f-7c3b-45bc-af71-5da356db4fb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='c_v66B56BB498ED4B16A56D62EFFDD04C7C80_3_1']</value>
      <webElementGuid>d16f2689-9fb2-42ef-9bdc-ada673febbf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='downFieldGroupc_v66B56BB498ED4B16A56D62EFFDD04C7C80_3_1']/div/label</value>
      <webElementGuid>b693c3e6-9806-4ce5-a375-4f3ec23758fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::label[2]</value>
      <webElementGuid>089fd940-0a39-463f-b9e7-2e0858bc3539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Make:']/parent::*</value>
      <webElementGuid>b6f30668-7ce4-463f-b1a2-864db002acfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/label</value>
      <webElementGuid>fd7c665b-8bad-4841-b472-f0912990d804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'c_v66B56BB498ED4B16A56D62EFFDD04C7C80_3_1' and (text() = 'Make:*' or . = 'Make:*')]</value>
      <webElementGuid>ee9fce62-9d68-4178-b3b8-b877a7175335</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
